sudo: required
language: rust

matrix:
  include:
    - rust: nightly
      script:
      # - ./ci/travis.sh
      # - cargo bench --all --no-run
      - ./ci/publish-docs.sh
    - rust: beta
      script:
      - ./ci/travis.sh
